{% set name = "aestream" %}
{% set version = "0.6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aestream-{{ version }}.tar.gz
  sha256: 2ce8f653bf7a3e44873ea9924a68bb696fbcfeb30fb10f8727362c8e095d99c5
  patches:
    - unvendor.patch

build:
  number: 6
  skip: true  # [win]
  ignore_run_exports_from:
    # cmake cannot find boost without libboost-devel but it is not needed at runtime
    - libboost-devel  # [linux]
    # flatbuffers only needed at build time
    - flatbuffers

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - pkg-config
    - cmake
    - make
    - python                                 # [build_platform != target_platform]
    - pip                                    # [build_platform != target_platform]
    - scikit-build-core                      # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - nanobind                               # [build_platform != target_platform]
  host:
    - scikit-build-core
    - python
    - nanobind
    - setuptools-scm
    - pip
    - libcaer
    - libopencv
    - flatbuffers
    - lz4-c
    - cli11
    - sdl2
    - libboost-devel  # [linux]
    - libboost-headers
  run:
    - python
    - numpy
    - pysdl2

test:
  imports:
    - aestream
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Streaming library for Address-Event Representation (AER) data
  license: MIT
  license_file: LICENSE
  home: https://github.com/aestream/aestream

extra:
  recipe-maintainers:
    - Tobias-Fischer
