{% set name = "aestream" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aestream-{{ version }}.tar.gz
  sha256: eeaa9dc49465bf25de80a549b78ee767cf3b34c1047caeb42be5e089d003d0ad
  patches:
    - unvendor.patch

build:
  number: 0
  skip: true  # [win]
  ignore_run_exports_from:
    # cmake cannot find boost without libboost-devel but it is not needed at runtime
    - libboost-devel  # [linux]
    # flatbuffers only needed at build time
    - flatbuffers

requirements:
  build:
    - {{ compiler('cxx') }}
    - pkg-config
    - cmake
    - make
    - python                                 # [build_platform != target_platform]
    - pip                                    # [build_platform != target_platform]
    - scikit-build-core                      # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - nanobind                               # [build_platform != target_platform]
  host:
    - scikit-build-core
    - python
    - nanobind
    - setuptools-scm
    - pip
    - libcaer
    - flatbuffers
    - lz4-c
    - cli11
    - sdl2
    - libboost-devel  # [linux]
    - libboost-headers
  run:
    - python
    - numpy
    - pysdl2
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  imports:
    - aestream
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Streaming library for Address-Event Representation (AER) data
  license: MIT
  license_file: LICENSE
  home: https://github.com/aestream/aestream

extra:
  recipe-maintainers:
    - Tobias-Fischer
